### ISSUE TITLE
0.1.0 does not match version regex

### ISSUE THREAD

**Issue by michaeljoy** [tentwentyfour/puppet-graylog-collector-sidecar#5]
The version regex only works with the alpha / beta builds and breaks on the 0.1.0 GA as it does not have the additional version components required in the selector logic for breaking down the version numbers. Changes necessary to make 0.1.0 installable with this module.

**Comment by kwisatz** [comment]
Thanks for your notification. We'll look into this ASAP.

**Comment by kwisatz** [comment]
This should be fixed in [tag 0.3.1](https://github.com/tentwentyfour/puppet-graylog-collector-sidecar/releases/tag/0.3.1). I tested it on our infrastructure.
Please let me know if you experience any other problems.

**Comment by kwisatz** [comment]
I'm going to close this. Please feel free to re-open should you experience more problems with the version regex.
